### ISSUE TITLE
Where is the complexity level annotated?

### ISSUE THREAD

**Issue by sunlightsgy** [A2Zadeh/Social-IQ#2]
I see in the raw files in 'qa' directory, but I could only find a list of 'a' and 'i'. Where is the complexity level annotated? If 'a' stands for 'advanced' and 'i' stands for 'intermediate', then what is the correct answers?

**Comment by A2Zadeh** [comment]
Hello @sunlightsgy. No that is `a` for `answer` and `i` for `incorrect answer`. Good point. We forgot to pack that information in the raw zip. I will try to update it in the next few days. We made changes to the question orders so I just have to check the complexity remains in order with the new question order in the zip files.

**Comment by A2Zadeh** [comment]
@sunlightsgy just wanted to give you an update. This issue was taking a bit longer, we are just done with ICLR deadline. I will update you in the next few days.

**Comment by A2Zadeh** [comment]
@sunlightsgy I update the main raw files of Social-IQ. The difficulty scores are there. Let me know if you had any other questions.

**Comment by Axe--** [comment]
Are the difficulty scores only provided for the public test-set? 
(Couldn't find those files in the raw data)
