### ISSUE TITLE
BERT text modality input

### ISSUE THREAD

**Issue by iyamabhishek** [A2Zadeh/Social-IQ#4]
Hi @A2Zadeh,

I wanted to feed texts to BERT to get their embeddings. How is this handled in the Social-IQ dataset? Extending issue #3, how is the different sentence length handled in the Social-IQ and do you use the uncased BERT model?

**Comment by iyamabhishek** [comment]
Referencing issue #3 and the current issue, is there an update on how different sentence length are handled in the Social-IQ and the BERT model?

**Comment by A2Zadeh** [comment]
@iyamabhishek sorry this fell through the cracks. Different lengths are handled by extending the model with paddings on the right. I can look more in details and see what exactly I put in as the pad character, but I think BERT tokenizer already had a predefined padding, perhaps I used CLS token, but I have to double check.

**Comment by iyamabhishek** [comment]
Thank you for double-checking the implementation! 

I mainly want to know three things:
1. BERT embedding dimension 
2. What was the max_len for sentence padding? And since BERT splits words, how did you ensure that the max_len wasn't violated?
3. Did you use the cased/uncased BERT model?

**Comment by A2Zadeh** [comment]
@iyamabhishek 

1. 768 * 12 (each layer of bert for each word). If too big then only last layer picked.

2. 512 is the size for BERT. so after tokenization, 512-len.

3. uncased.

**Comment by iyamabhishek** [comment]
Awesome! 
Thanks for the reply. This clears most of my doubts.

You mentioned 768*12. Does 12 mean the number of tokens after tokenization for each sentence? I am still confused about 12.

Example:
Sentence: I have a house
Number of tokens after tokenization: 4
In this case, will the padding be 8 (12-4) or 508 (512-4)?

**Comment by A2Zadeh** [comment]
Awesome, happy to help!

There are 12 layers in BERT. I extract embedding from each of them, sort of like ELMO style.

**Comment by iyamabhishek** [comment]
Ah, this makes so much more sense now. Thank you!

When you say ELMO style, how do you assign weights to each word for the weighted avg?

**Comment by A2Zadeh** [comment]
@iyamabhishek I didn't particularly add that to the final code, since I tried learning coefficients for each layer embeddings, but it didn't make a big difference. But feel free to try to learn the coefficient end to end, maybe I missed something.

**Comment by iyamabhishek** [comment]
Sure, thanks a lot for all the pointer! Your comments helped me in understanding how BERT was used for Social-IQ.
Closing the issue now.

**Comment by A2Zadeh** [comment]
@iyamabhishek Happy to help!
