### ISSUE TITLE
Num of Transcript Files is only 831 (total 1015)

### ISSUE THREAD

**Issue by Axe--** [A2Zadeh/Social-IQ#8]
The total **transcript** files in the raw data = 831,
While the count for QA, Acoustic & Video = 1015

**Comment by A2Zadeh** [comment]
Hello @Axe--. We have taken down ~270 transcripts since they were not >95% correct. Currently we are sending them for re-transcription. We will subsequently update the data.

**Comment by Axe--** [comment]
Hey, thanks for update!

**Comment by A2Zadeh** [comment]
Of course. Closing this issue for now.
